### ISSUE TITLE
Project Check #5 Homework

### ISSUE THREAD

**Issue by antonyrc6** [antonyrc6/Antony-s-fast-page#36]
- [x] [Binary Math Lesson](https://github.com/antonyrc6/Antony-s-fast-page/issues/30#issue-1689421804) 0.93/1
- [x] [Numpy Lesson](https://github.com/antonyrc6/Antony-s-fast-page/issues/31#issue-1689422062) 0.9/1
- [x] [Sqlite Lesson](https://github.com/antonyrc6/Antony-s-fast-page/issues/32#issue-1689803324) 0.9/1
- [x] [Data related to user Lesson](https://github.com/antonyrc6/Antony-s-fast-page/issues/33#issue-1689803615) 0.9/1
- [x] [Frontend and Backend Lesson](https://github.com/antonyrc6/Antony-s-fast-page/issues/35#issue-1691871442) 0.9/1
- Total:4.53/5
- [ ] MCQ 2021 (I did not finish the quiz)
